### ISSUE TITLE
Please provide installation guide

### ISSUE THREAD

**Issue by FabianNiesen** [jantari/rewinged#1]
Could you please provide a guide how to get it running on Windows Server? I will then try to work with your Solution.

**Comment by jantari** [comment]
You can download the preview releases: https://github.com/jantari/rewinged/releases

There's an executable for Windows and for Linux attached

**Comment by jantari** [comment]
Please let me know if you got it running or have further issues

**Comment by jantari** [comment]
I have also added a more complete getting started section to the readme with [563f7e7](https://github.com/jantari/rewinged/commit/563f7e721bee16e2fdd2159bd73cb01b09aa512d), so I'll close this as completed
