### ISSUE TITLE
Issue Adding New Repository Source with Winget

### ISSUE THREAD

**Issue by gauchim** [jantari/rewinged#5]
I am encountering an issue while trying to add a new repository source using Winget, following the rewinged setup. The steps I followed are:
1. I generated a self-signed certificate using the command:
```bash
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout private.key -out cert.pem
```
2. Downloaded and ran the "rewinged" binary with the command:
```bash
./rewinged -https -listen 0.0.0.0:8443
```
When attempting to add the new repository from Winget with the commands:
```bash
PS C:\Users\Administrador> winget source add --name uibstore --arg https://10.100.128.8:8443/api --type "Microsoft.Rest"
No se pudo abrir el origen agregado.
PS C:\Users\Administrador> winget source add --name uibstore --arg https://10.100.128.8:8443/api
Agregando origen:
  uibstore -> https://10.100.128.8:8443/api
Se ha producido un error inesperado al ejecutar el comando:
0x80072efd : unknown error
PS C:\Users\Administrador>
```
I suspect the issue might be related to the self-signed certificate not being trusted by Winget, but I'm not certain. I followed the instructions for using "rewinged" precisely as described. I would appreciate any guidance or solutions to resolve this problem. Thanks.

**Comment by jantari** [comment]
Did you add the certificate you generated to Windows' trusted root certificates store?

What output do you get when you try `curl.exe -v https://10.100.128.8:8443/api/information`?

**Comment by gauchim** [comment]
Hello,

I had generated the certificate from my Linux machine:
```bash
$ openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout selfsigned.key -out selfsigned.crt
```

Apparently it is not created correctly. I created it using PowerShell script and now it works like a charm!

Thank you!

**Comment by gauchim** [comment]
Hello,

I had generated the certificate from my Linux machine:
```bash
$ openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout selfsigned.key -out selfsigned.crt
```

Apparently it is not created correctly. I created it using PowerShell script and now it works like a charm!

Thank you!
