### ISSUE TITLE
cli 

### ISSUE THREAD

**Issue by gedw99** [jantari/rewinged#9]
Hey @jantari 

This server looks really good for the EU Project Science Team. 

It looks like it will allow us to manage installation of custom software via manifests ?

Is there a golangCLI to talk to the resigned server over http ?

I am also looking for  a golang CLI for Clients that could be installed on Guests, that speaks to the Windows native winget system ?  https://github.com/sheepla/fzwinget is one, but it needs a bit of work I think.

**Comment by jantari** [comment]
Hi,

you can use `curl` (or similar) to interact with the API, but it's mostly intended for the official winget tool. If you want an alternative CLI don't forget there's also the official [winget PowerShell module](https://www.powershellgallery.com/packages/Microsoft.Winget.Client). Other than that I'm not aware of third-party alternatives and have never tried any.
